services:
  - type: web
    name: pathashilpa-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore # or frankfurt/oregon
    envVars:
      - key: PORT
        value: 8000
      - key: ENV
        value: production
      - key: FAL_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: BHASHINI_API_KEY
        sync: false
      - key: BHASHINI_USER_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
